version: '2.1'

volumes:
    gareport:


services:

  proxy:
    image: nginx:1.13-alpine
    ports:
      - '80:80'
      - '443:443'
      - '7890:7890'
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/conf.d:/etc/nginx/conf.d:ro
      - ./conf/ssl:/etc/ssl:ro
      - ./conf/htpasswd:/etc/nginx/htpasswd:ro
      - ./logs:/var/log/nginx:rw
      - gareport:/usr/share/nginx/html:ro
    depends_on:
      - goaccess
    restart: unless-stopped

  goaccess:
    image: allinurl/goaccess
    #ports:
    #  - '7890:7890'
    volumes:
      - ./conf:/srv/data:ro
      - ./logs/parse:/srv/logs:ro
      - gareport:/srv/report:rw
    restart: unless-stopped


## proxy should connect to an already
## created and external network:
#networks:
#  default:
#    external:
#      name: reverse-proxy
